---
title: "DMSD Vignette"
author: "Flávio Mota"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{DMSD-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Loading data
```{r, fig.height = 5, fig.width = 8, fig.align = 'center',}
library(terra)
library(BAT)
library(DMSD)

# Create SpatRaster objects
set.seed(100)
bin1 <- terra::rast(ncol = 5, nrow = 5, nlyr = 10)
values(bin1) <- round(runif(ncell(bin1) * nlyr(bin1)))
names(bin1) <- paste0("sp", 1:10)
bin1

bin2 <- terra::rast(ncol = 5, nrow = 5, nlyr = 10)
values(bin2) <- round(runif(ncell(bin2) * nlyr(bin2)))
names(bin2) <- names(bin1)
bin2

# Create data.frame object
set.seed(100)
mass <- runif(10, 10, 800)
beak.size <- runif(10, .2, 5)
tail.length <- runif(10, 2, 10)
wing.length <- runif(10, 15, 60)
range.size <- runif(10, 10000, 100000)
traits <- data.frame(mass, beak.size, tail.length, wing.length, range.size)
rownames(traits) <- names(bin1)
traits

# Create phylo object
set.seed(100)
tree <- ape::rtree(n = 10, tip.label = names(bin1))
tree
```

## Alpha diversity
```{r, fig.height = 4, fig.width = 5, fig.align = 'center',}
# Taxonomic
alpha.td <- spat.alpha(bin1)
alpha.td
terra::plot(alpha.td)

# Functional
alpha.fd <- spat.alpha(bin1, traits)
alpha.fd
terra::plot(alpha.fd)

# Phylogenetic
alpha.pd <- spat.alpha(bin1, tree)
alpha.pd
terra::plot(alpha.pd)
```

## Spatial beta diversity
```{r, fig.height = 4, fig.width = 5, fig.align = 'center',}
# Taxonomic
beta.td <- spat.beta(bin1)
beta.td
terra::plot(beta.td)

# Functional
beta.fd <- spat.beta(bin1, traits)
beta.fd
terra::plot(beta.fd)

# Phylogenetic
beta.pd <- spat.beta(bin1, tree)
beta.pd
terra::plot(beta.pd)
```

## Temporal beta diversity
```{r, fig.height = 4, fig.width = 5, fig.align = 'center',}
# Taxonomic
betatemp.td <- temp.beta(bin1, bin2)
betatemp.td
terra::plot(betatemp.td)

# Functional
betatemp.fd <- temp.beta(bin1, bin2, traits)
betatemp.fd
terra::plot(betatemp.fd)

# Phylogenetic
betatemp.pd <- temp.beta(bin1, bin2, tree)
betatemp.pd
terra::plot(betatemp.pd)
```
